services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: tech-support-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: defaultuser
      POSTGRES_PASSWORD: defaultpassword
      POSTGRES_DB: defaultdb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U defaultuser -d defaultdb"]
      interval: 10s
      timeout: 5s
      retries: 5
